# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 354d9ee209e08ab52b292e9fe599e178ba1b14aa067addea498e21d4d698b71d5e93651b0560d765b518e088db34875c92078a3b7f47085c702750ed21a1bcf1

test:
  secret_key_base: 32f89bc8cb0c2950709e94a250e31159a26cf9321c2ec2b2cfcddd332e84eadbe5d29bfffe8835ef450e7ffab8d218ccb992c771b7215ca351cc5f04107da416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
